/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ErrorsMap model module.
* @module model/ErrorsMap
* @version v1
*/
export default class ErrorsMap {
    /**
    * Constructs a new <code>ErrorsMap</code>.
    * @alias module:model/ErrorsMap
    * @class
    * @extends Object
    */

    constructor() {
        
        
        return this;
    }

    /**
    * Constructs a <code>ErrorsMap</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorsMap} obj Optional instance to populate.
    * @return {module:model/ErrorsMap} The populated <code>ErrorsMap</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorsMap();
            ApiClient.constructFromObject(data, obj, 'Array');
            
            
        }
        return obj;
    }





}
