/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvitationInvitation from './InvitationInvitation';

/**
* The Invitation model module.
* @module model/Invitation
* @version v1
*/
export default class Invitation {
    /**
    * Constructs a new <code>Invitation</code>.
    * @alias module:model/Invitation
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Invitation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Invitation} obj Optional instance to populate.
    * @return {module:model/Invitation} The populated <code>Invitation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Invitation();
                        
            
            if (data.hasOwnProperty('invitation')) {
                obj['invitation'] = InvitationInvitation.constructFromObject(data['invitation']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/InvitationInvitation} invitation
    */
    'invitation' = undefined;




}
