/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InvitationInvitation model module.
* @module model/InvitationInvitation
* @version v1
*/
export default class InvitationInvitation {
    /**
    * Constructs a new <code>InvitationInvitation</code>.
    * @alias module:model/InvitationInvitation
    * @class
    * @param inviteeName {String} 
    * @param inviteeEmail {String} 
    */

    constructor(inviteeName, inviteeEmail) {
        
        
        this['invitee_name'] = inviteeName;
        this['invitee_email'] = inviteeEmail;
        
    }

    /**
    * Constructs a <code>InvitationInvitation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InvitationInvitation} obj Optional instance to populate.
    * @return {module:model/InvitationInvitation} The populated <code>InvitationInvitation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvitationInvitation();
                        
            
            if (data.hasOwnProperty('invitee_title')) {
                obj['invitee_title'] = ApiClient.convertToType(data['invitee_title'], 'String');
            }
            if (data.hasOwnProperty('invitee_name')) {
                obj['invitee_name'] = ApiClient.convertToType(data['invitee_name'], 'String');
            }
            if (data.hasOwnProperty('invitee_email')) {
                obj['invitee_email'] = ApiClient.convertToType(data['invitee_email'], 'String');
            }
            if (data.hasOwnProperty('slack_uid')) {
                obj['slack_uid'] = ApiClient.convertToType(data['slack_uid'], 'String');
            }
            if (data.hasOwnProperty('invitee_company')) {
                obj['invitee_company'] = ApiClient.convertToType(data['invitee_company'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} invitee_title
    */
    'invitee_title' = undefined;
    /**
    * @member {String} invitee_name
    */
    'invitee_name' = undefined;
    /**
    * @member {String} invitee_email
    */
    'invitee_email' = undefined;
    /**
    * @member {String} slack_uid
    */
    'slack_uid' = undefined;
    /**
    * @member {String} invitee_company
    */
    'invitee_company' = undefined;




}
