/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobsData from './JobsData';
import JobsMeta from './JobsMeta';
import JobsPagination from './JobsPagination';

/**
* The Jobs model module.
* @module model/Jobs
* @version v1
*/
export default class Jobs {
    /**
    * Constructs a new <code>Jobs</code>.
    * @alias module:model/Jobs
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Jobs</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Jobs} obj Optional instance to populate.
    * @return {module:model/Jobs} The populated <code>Jobs</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Jobs();
                        
            
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [JobsData]);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = JobsMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = JobsPagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/JobsData>} data
    */
    'data' = undefined;
    /**
    * @member {module:model/JobsMeta} meta
    */
    'meta' = undefined;
    /**
    * @member {module:model/JobsPagination} pagination
    */
    'pagination' = undefined;




}
