/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The JobsPagination model module.
* @module model/JobsPagination
* @version v1
*/
export default class JobsPagination {
    /**
    * Constructs a new <code>JobsPagination</code>.
    * @alias module:model/JobsPagination
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>JobsPagination</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/JobsPagination} obj Optional instance to populate.
    * @return {module:model/JobsPagination} The populated <code>JobsPagination</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsPagination();
                        
            
            if (data.hasOwnProperty('current_page')) {
                obj['current_page'] = ApiClient.convertToType(data['current_page'], 'Number');
            }
            if (data.hasOwnProperty('last_page')) {
                obj['last_page'] = ApiClient.convertToType(data['last_page'], 'Number');
            }
            if (data.hasOwnProperty('next_page_url')) {
                obj['next_page_url'] = ApiClient.convertToType(data['next_page_url'], 'String');
            }
            if (data.hasOwnProperty('prev_page_url')) {
                obj['prev_page_url'] = ApiClient.convertToType(data['prev_page_url'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} current_page
    */
    'current_page' = undefined;
    /**
    * @member {Number} last_page
    */
    'last_page' = undefined;
    /**
    * @member {String} next_page_url
    */
    'next_page_url' = undefined;
    /**
    * @member {String} prev_page_url
    */
    'prev_page_url' = undefined;




}
