/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The JobsAttributes model module.
* @module model/JobsAttributes
* @version v1
*/
export default class JobsAttributes {
    /**
    * Constructs a new <code>JobsAttributes</code>.
    * @alias module:model/JobsAttributes
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>JobsAttributes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/JobsAttributes} obj Optional instance to populate.
    * @return {module:model/JobsAttributes} The populated <code>JobsAttributes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsAttributes();
                        
            
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('salary')) {
                obj['salary'] = ApiClient.convertToType(data['salary'], 'String');
            }
            if (data.hasOwnProperty('creator_name')) {
                obj['creator_name'] = ApiClient.convertToType(data['creator_name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} title
    */
    'title' = undefined;
    /**
    * @member {String} currency
    */
    'currency' = undefined;
    /**
    * @member {String} salary
    */
    'salary' = undefined;
    /**
    * @member {String} creator_name
    */
    'creator_name' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {String} last_updated
    */
    'last_updated' = undefined;




}
