/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The JobsMeta model module.
* @module model/JobsMeta
* @version v1
*/
export default class JobsMeta {
    /**
    * Constructs a new <code>JobsMeta</code>.
    * @alias module:model/JobsMeta
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>JobsMeta</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/JobsMeta} obj Optional instance to populate.
    * @return {module:model/JobsMeta} The populated <code>JobsMeta</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobsMeta();
                        
            
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} total
    */
    'total' = undefined;




}
