/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UsersAttributes model module.
* @module model/UsersAttributes
* @version v1
*/
export default class UsersAttributes {
    /**
    * Constructs a new <code>UsersAttributes</code>.
    * @alias module:model/UsersAttributes
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UsersAttributes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UsersAttributes} obj Optional instance to populate.
    * @return {module:model/UsersAttributes} The populated <code>UsersAttributes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersAttributes();
                        
            
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('tilde_url')) {
                obj['tilde_url'] = ApiClient.convertToType(data['tilde_url'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('biography')) {
                obj['biography'] = ApiClient.convertToType(data['biography'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('twitter_handle')) {
                obj['twitter_handle'] = ApiClient.convertToType(data['twitter_handle'], 'String');
            }
            if (data.hasOwnProperty('confirmed')) {
                obj['confirmed'] = ApiClient.convertToType(data['confirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('confirmed_at')) {
                obj['confirmed_at'] = ApiClient.convertToType(data['confirmed_at'], 'String');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} first_name
    */
    'first_name' = undefined;
    /**
    * @member {String} last_name
    */
    'last_name' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {String} nickname
    */
    'nickname' = undefined;
    /**
    * @member {String} tilde_url
    */
    'tilde_url' = undefined;
    /**
    * @member {String} location
    */
    'location' = undefined;
    /**
    * @member {String} biography
    */
    'biography' = undefined;
    /**
    * @member {String} title
    */
    'title' = undefined;
    /**
    * @member {String} company_name
    */
    'company_name' = undefined;
    /**
    * @member {String} twitter_handle
    */
    'twitter_handle' = undefined;
    /**
    * @member {Boolean} confirmed
    */
    'confirmed' = undefined;
    /**
    * @member {String} confirmed_at
    */
    'confirmed_at' = undefined;
    /**
    * @member {String} last_updated
    */
    'last_updated' = undefined;




}
