/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ErrorsObject from '../model/ErrorsObject';
import Jobs from '../model/Jobs';

/**
* Jobs service.
* @module api/JobsApi
* @version v1
*/
export default class JobsApi {

    /**
    * Constructs a new JobsApi. 
    * @alias module:api/JobsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiV1JobsGet operation.
     * @callback module:api/JobsApi~apiV1JobsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Jobs} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * All jobs
     * @param {Object} opts Optional parameters
     * @param {module:api/JobsApi~apiV1JobsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Jobs}
     */
    apiV1JobsGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page[number]': opts['pageNumber']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Jobs;

      return this.apiClient.callApi(
        '/api/v1/jobs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
