/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiV1);
  }
}(this, function(expect, ApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiV1.InvitationInvitation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InvitationInvitation', function() {
    it('should create an instance of InvitationInvitation', function() {
      // uncomment below and update the code to test InvitationInvitation
      //var instane = new ApiV1.InvitationInvitation();
      //expect(instance).to.be.a(ApiV1.InvitationInvitation);
    });

    it('should have the property inviteeTitle (base name: "invitee_title")', function() {
      // uncomment below and update the code to test the property inviteeTitle
      //var instane = new ApiV1.InvitationInvitation();
      //expect(instance).to.be();
    });

    it('should have the property inviteeName (base name: "invitee_name")', function() {
      // uncomment below and update the code to test the property inviteeName
      //var instane = new ApiV1.InvitationInvitation();
      //expect(instance).to.be();
    });

    it('should have the property inviteeEmail (base name: "invitee_email")', function() {
      // uncomment below and update the code to test the property inviteeEmail
      //var instane = new ApiV1.InvitationInvitation();
      //expect(instance).to.be();
    });

    it('should have the property slackUid (base name: "slack_uid")', function() {
      // uncomment below and update the code to test the property slackUid
      //var instane = new ApiV1.InvitationInvitation();
      //expect(instance).to.be();
    });

    it('should have the property inviteeCompany (base name: "invitee_company")', function() {
      // uncomment below and update the code to test the property inviteeCompany
      //var instane = new ApiV1.InvitationInvitation();
      //expect(instance).to.be();
    });

  });

}));
