/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiV1);
  }
}(this, function(expect, ApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiV1.JobsAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JobsAttributes', function() {
    it('should create an instance of JobsAttributes', function() {
      // uncomment below and update the code to test JobsAttributes
      //var instane = new ApiV1.JobsAttributes();
      //expect(instance).to.be.a(ApiV1.JobsAttributes);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new ApiV1.JobsAttributes();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new ApiV1.JobsAttributes();
      //expect(instance).to.be();
    });

    it('should have the property salary (base name: "salary")', function() {
      // uncomment below and update the code to test the property salary
      //var instane = new ApiV1.JobsAttributes();
      //expect(instance).to.be();
    });

    it('should have the property creatorName (base name: "creator_name")', function() {
      // uncomment below and update the code to test the property creatorName
      //var instane = new ApiV1.JobsAttributes();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ApiV1.JobsAttributes();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "last_updated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instane = new ApiV1.JobsAttributes();
      //expect(instance).to.be();
    });

  });

}));
