/**
 * API V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiV1);
  }
}(this, function(expect, ApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiV1.UsersAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersAttributes', function() {
    it('should create an instance of UsersAttributes', function() {
      // uncomment below and update the code to test UsersAttributes
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be.a(ApiV1.UsersAttributes);
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property nickname (base name: "nickname")', function() {
      // uncomment below and update the code to test the property nickname
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property tildeUrl (base name: "tilde_url")', function() {
      // uncomment below and update the code to test the property tildeUrl
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property biography (base name: "biography")', function() {
      // uncomment below and update the code to test the property biography
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property twitterHandle (base name: "twitter_handle")', function() {
      // uncomment below and update the code to test the property twitterHandle
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property confirmed (base name: "confirmed")', function() {
      // uncomment below and update the code to test the property confirmed
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property confirmedAt (base name: "confirmed_at")', function() {
      // uncomment below and update the code to test the property confirmedAt
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "last_updated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instane = new ApiV1.UsersAttributes();
      //expect(instance).to.be();
    });

  });

}));
